// Generated by CoffeeScript 1.6.3
(function() {
  var NodeSet;

  NodeSet = (function() {
    function NodeSet(prototype) {
      if (typeof prototype !== 'function') {
        throw new TypeError('Invalid prototype');
      }
      this._proto = prototype;
      this.reset();
    }

    NodeSet.prototype.reset = function() {
      return this._store = [];
    };

    NodeSet.prototype.add = function(object) {
      if (!(object instanceof this._proto)) {
        throw new Error('Invalid Member Object');
      }
      this._store.push(object);
      return this;
    };

    NodeSet.prototype.count = function() {
      return this._store.length;
    };

    NodeSet.prototype.getData = function() {
      return this._store;
    };

    NodeSet.prototype.replace = function(array) {
      if (!Array.isArray(array)) {
        throw new TypeError('Invalid array');
      }
      return this._store = array;
    };

    return NodeSet;

  })();

  module.exports = NodeSet;

}).call(this);
